/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { defineComponent, h } from 'vue';
import MkFolder from '@/components/MkFolder.vue';
import MkCode from '@/components/MkCode.vue';
import { i18n } from '@/i18n';

export const LCFContexts = {
	InspectionSubject: {
		component: defineComponent(() => {
			return () => h(MkFolder, null, {
				label: () => [i18n.ts._lcfExpression.inputContext, ': ', h('code', 'InspectionSubject')],
				default: () => h(MkCode, {
					lang: 'typescript',
					code: [
						'type InspectionSubject = {',
						'\tuserId: string;',
						'\ttext: string | null;',
						'\treply: MiNote | null;',
						'\trenote: MiNote | null;',
						'\tfiles: MiDriveFile[] | null;',
						'\tmentions: { username: string; host: string | null; }[];',
						'\ttags: string[];',
						'\troles: MiRole[];',
						'\tflags: MiNoteFlag[];',
						'}',
						'',
						'type MiNote = {',
						'\tid: string;',
						'\treplyId: string | null;',
						'\trenoteId: string | null;',
						'\tthreadId: string | null;',
						'\ttext: string | null;',
						'\tname: string | null;',
						'\tcw: string | null;',
						'\tuserId: string;',
						'\tlocalOnly: boolean;',
						'\treactionAcceptance: "likeOnly" | "likeOnlyForRemote" | "nonSensitiveOnly" | "nonSensitiveOnlyForLocalLikeOnlyForRemote" | null;',
						'\trenoteCount: number;',
						'\trepliesCount: number;',
						'\tclippedCount: number;',
						'\tpageCount: number;',
						'\treactions: {[K in string]: number};',
						'\tvisibility: "public" | "home" | "followers" | "specified";',
						'\turi: string | null;',
						'\turl: string | null;',
						'\tfileIds: string[];',
						'\tattachedFileTypes: string[];',
						'\tvisibleUserIds: string[];',
						'\tmentions: string[];',
						'\tmentionedRemoteUsers: string;',
						'\treactionAndUserPairCache: string[];',
						'\temojis: string[];',
						'\ttags: string[];',
						'\thasPoll: boolean;',
						'\tchannelId: string | null;',
						'\tuserHost: string | null;',
						'\treplyUserId: string | null;',
						'\treplyUserHost: string | null;',
						'\trenoteUserId: string | null;',
						'\trenoteUserHost: string | null;',
						'\trenoteChannelId: string | null;',
						'}',
						'',
						'type MiDriveFile = {',
						'\tid: string;',
						'\tuserId: string | null;',
						'\tuserHost: string | null;',
						'\tmd5: string;',
						'\tname: string;',
						'\ttype: string;',
						'\tsize: number;',
						'\tcomment: string | null;',
						'\tblurhash: string | null;',
						'\tproperties: { width?: number; height?: number; orientation?: number; avgColor?: string };',
						'\tstoredInternal: boolean;',
						'\turl: string;',
						'\tthumbnailUrl: string | null;',
						'\twebpublicUrl: string | null;',
						'\twebpublicType: string | null;',
						'\taccessKey: string | null;',
						'\tthumbnailAccessKey: string | null;',
						'\twebpublicAccessKey: string | null;',
						'\turi: string | null;',
						'\tsrc: string | null;',
						'\tfolderId: string | null;',
						'\tisSensitive: boolean;',
						'\tmaybeSensitive: boolean;',
						'\tmaybePorn: boolean;',
						'\tisLink: boolean;',
						'\trequestHeaders: {[K in string]: string} | null;',
						'\trequestIp: string | null;',
						'}',
						'',
						'type MiRole = {',
						'\tid: string;',
						'\tupdatedAt: Date;',
						'\tlastUsedAt: Date;',
						'\tname: string;',
						'\tdescription: string;',
						'\tcolor: string | null;',
						'\ticonUrl: string | null;',
						'\ttarget: "manual" | "conditional";',
						'\tcondFormula: RoleCondFormulaValue;',
						'\tisPublic: boolean;',
						'\tasBadge: boolean;',
						'\tisModerator: boolean;',
						'\tisAdministrator: boolean;',
						'\tisExplorable: boolean;',
						'\tpreserveAssignmentOnMoveAccount: boolean;',
						'\tcanEditMembersByModerator: boolean;',
						'\tdisplayOrder: number;',
						'\tpolicies: {[K in string]: { useDefault: boolean; priority: number; value: any; }};',
						'}',
						'',
						'type MiNoteFlag = {',
						'\tid: string;',
						'\tupdatedAt: Date;',
						'\tname: string;',
						'\tdescription: string;',
						'\tcolor: string | null;',
						'\ticonUrl: string | null;',
						'\tisPublic: boolean;',
						'\tasBadge: boolean;',
						'\tcanAssignByUser: boolean;',
						'\tdisplayOrder: number;',
						'\ttarget: "manual" | "conditional";',
						'\tcondFormula: string;',
						'\tpolicies: NotePolicyOverrides;',
						'}',
					].join('\n'),
				}),
			});
		}),
	},
} as const;
